//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TestWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Test), typeof(System.Object));
		L.RegFunction("Speak", Speak);
		L.RegFunction("New", _CreateTest);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTest(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Test obj = new Test();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Test.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Speak(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Test obj = (Test)ToLua.CheckObject<Test>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.Speak(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

